import {
  MessageSquare,
  FileText,
  Cog,
  CheckCircle,
  Code,
  Database,
  Globe,
  Palette,
  Target,
  TrendingUp,
  Award,
  Lightbulb,
  Users,
  Network,
  Megaphone,
  Briefcase,
  Building2,
  Home,
  MessageCircleQuestion,
  UserPlus,
  Shield,
  Zap,
  UsersRound,
  FileUser,
  DoorOpen,
  Flag,
  AlarmClock,
  Mail,
  Scale,
  Loader2,
  AlertTriangle,
  Info,
  AlertCircle,
  RefreshCw,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowUpDown,
  ArrowLeftRight,
  Plus,
  Save,
  Calculator,
  Book,
  ShoppingCart,
} from 'lucide-react';

import { IconName } from './index.types';

// Mappa esportata come una costante immutabile.
export const iconMap = {
  'message-square': MessageSquare,
  'file-text': FileText,
  'cog': Cog,
  'check-circle': CheckCircle,
  'code': Code,
  'palette': Palette,
  'database': Database,
  'globe': Globe,
  'trending-up': TrendingUp,
  'target': Target,
  'users': Users,
  'lightbulb': Lightbulb,
  'award': Award,
  'network': Network,
  'megaphone': Megaphone,
  'home': Home,
  'building2': Building2,
  'user-plus': UserPlus,
  'briefcase': Briefcase,
  'message-circle-question': MessageCircleQuestion,
  'shield': Shield,
  'zap': Zap,
  'user-round': UsersRound,
  'file-user': FileUser,
  'door-open': DoorOpen,
  'flag': Flag,
  'alarm-clock': AlarmClock,
  'scale': Scale,
  'mail': Mail,
  'loader-2': Loader2,
  'alert-triangle': AlertTriangle,
  'info': Info,
  'alert-circle': AlertCircle,
  'refresh-cw': RefreshCw,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up-down': ArrowUpDown,
  'arrow-left-right': ArrowLeftRight,
  'plus': Plus,
  'save': Save,
  'calculator': Calculator,
  'book': Book,
  'shopping-cart': ShoppingCart,
} as const;

/**
 * Controlla se una stringa è un nome di icona valido.
 * @param name La stringa da controllare.
 * @returns `true` se il nome è una chiave valida di iconMap, altrimenti `false`.
 */
export const isIconName = (name: string): name is IconName => {
  return name in iconMap;
};
